#pragma config(Motor,  motor1,          leftWheel,     tmotorVexIQ, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  motor6,          rightWheel,    tmotorVexIQ, PIDControl, driveRight, encoder)
#pragma config(Motor,  motor7,          leftArm,       tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor8,          rightArm,      tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while (true)
{
	tankControl(ChD, ChA, 10);
	armControl(leftArm, BtnLUp, BtnLDown, 100);
	armControl(rightArm, BtnLUp, BtnLDown, 100);
}


}
