#pragma config(Sensor, port5,  armgyro,        sensorVexIQ_Gyro)
#pragma config(Motor,  motor7,          leftArm,       tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor8,          rightArm,      tmotorVexIQ, PIDControl, reversed, encoder)
//#pragma config(Motor,  motor1,          leftWheel,     tmotorVexIQ, PIDControl, reversed, driveLeft, encoder)
//#pragma config(Motor,  motor6,          rightWheel,    tmotorVexIQ, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Go to degrees claw
void clawUp() {
	if (getGyroDegrees(armgyro)<275) {
		setMultipleMotors(100, motor7, motor8);
		waitUntil(getGyroDegrees(armgyro)==125);
		stopMotor(motor7);
		stopMotor(motor8);
	}
}

//Main event loop
task main()
{
	bool e1pressed;
	e1pressed = false;
	while (true)
	{
		//tankControl(ChD, ChA, 10);
		//armControl(leftArm, BtnLUp, BtnLDown, 100);
		//armControl(rightArm, BtnLUp, BtnLDown, 100);
		if (getJoystickValue(BtnEUp)==1&&e1pressed==false) {
			clawUp();
			e1pressed = true;
		}
		if (getJoystickValue(BtnEUp)==0&&e1pressed==true) {
			e1pressed=false;
		}
	}


}
