#pragma config(Motor,  motor1,          LeftWheel,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor6,          RightWheel,    tmotorVexIQ, PIDControl, driveRight, encoder)
#pragma config(Motor,  motor10,         ArmOne,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,         ArmTwo,        tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
While (true)[


}
